core/urls.py
from django.urls import path
from .views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete

projects_patterns = ([
    path('', ProjectListView.as_view(), name='projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
], 'projects')

webplayground/urls.py
from django.contrib import admin
from django.urls import path, include
from profiles.urls import profiles_patterns
from projects.urls import projects_patterns
from scraper.urls import scraper_patterns
from patentes.urls import patentes_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    # Paths de profiles
    path('profiles/', include(profiles_patterns)),
    # Paths de proyectos
    path('projects/', include(projects_patterns)),
    # Paths de ecuación
    path('scraper/', include(scraper_patterns)),
    # Paths de patentes
    path('patentes/', include(patentes_patterns)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Nombre", max_length=200)
    description = models.TextField(verbose_name="Descripción",null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición") 

    class Meta:
        ordering = ['user__username']

def __str__(self):
        return self.title
    

scraper/models.py
from django.db import models
from projects.models import Project
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.
#Ecuaciones
class Ecuacion(models.Model):
    ecuacion = models.CharField(max_length=300, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    proyecto = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'ecuacion'
        verbose_name = "ecuacion"
        verbose_name_plural = "ecuaciones"
        ordering = ['proyecto']

    def __str__(self):
        return self.ecuacion

class Estados(models.Model):
    desc_estado = models.CharField(unique=True, max_length=250)

    class Meta:
        db_table = 'estados'
        verbose_name = "estado"
        verbose_name_plural = "estados"
        ordering = ['desc_estado']

    def __str__(self):
        return self.desc_estado

class Tiposcip(models.Model):
    desc_tip_cip = models.CharField(db_column='desc_tip_cip', max_length=50,verbose_name='tipo de cip')  # Field name made lowercase.

    class Meta:
        db_table = 'tipos_cip'
        verbose_name = "tipo_cip"
        verbose_name_plural = "tipos_cip"
        ordering = ['desc_tip_cip']

    def __str__(self):
        return self.desc_tip_cip

class cip(models.Model):
    cod_cip = models.CharField(db_column='cod_cip', unique=True, max_length=45)  # Field name made lowercase.
    desc_cip = models.TextField(db_column='desc_cip', blank=True, null=True)  # Field name made lowercase.
    parent_cip = models.IntegerField(db_column='parent_cip', blank=True, null=True)  # Field name made lowercase.
    tipo_cip = models.ForeignKey('Tiposcip', on_delete=models.CASCADE, db_column='tipo_cip_id')  # Field name made lowercase.

    class Meta:
        db_table = 'cip'
        verbose_name = "cip"
        verbose_name_plural = "cips"
        ordering = ['cod_cip']

    def __str__(self):
        return self.cod_cip

#patente
class Patentes(models.Model):
    titulo_patente = models.CharField(max_length=300)
    resumen_patente = models.TextField(blank=True, null=True)
    claims_patente = models.TextField(blank=True, null=True)
    estado = models.ForeignKey(Estados, on_delete=models.CASCADE)
    clasificacion = models.ForeignKey(cip, on_delete=models.CASCADE)
    ecuacion_id = models.ForeignKey(Ecuacion,on_delete=models.CASCADE)

    class Meta:
        db_table = 'patentes'
        verbose_name = "patente"
        verbose_name_plural = "patentes"

    def __str__(self):
        return self.titulo_patente


class Paises(models.Model):
    cod_pais = models.CharField(max_length=2)
    desc_pais = models.CharField(max_length=200)

    class Meta:
        db_table = 'paises'
        verbose_name = "pais"
        verbose_name_plural = "paises"
        ordering = ['desc_pais']

    def __str__(self):
        return self.desc_pais

class TipoNumero(models.Model):
    nombre_tipo_numero = models.CharField(max_length=50)

    class Meta:
        db_table = 'tipo_numero'
        verbose_name = "tipo_numero"
        verbose_name_plural = "tipos_numeros"
        ordering = ['nombre_tipo_numero']

    def __str__(self):
        return self.nombre_tipo_numero
		
class NumerosPatentes(models.Model):
    cod_serie_patente = models.CharField(max_length=30)
    fecha_numero_patente = models.DateField()
    num_pat_pais = models.ForeignKey('Paises', on_delete=models.CASCADE)
    tipo_numero = models.ForeignKey('TipoNumero', on_delete=models.CASCADE)
    patente = models.ForeignKey('Patentes', on_delete=models.CASCADE)

    class Meta:
        db_table = 'numeros_patentes'
        verbose_name = "numero_patente"
        verbose_name_plural = "numeros_patentes"

#Repositorio
class Repositorios(models.Model):
    nombre_repositorio = models.CharField(max_length=50)
    link_repositorio = models.CharField(max_length=100)

    class Meta:
        db_table = 'repositorios'
        verbose_name = "repositorio"
        verbose_name_plural = "repositorios"
        ordering = ['nombre_repositorio']

    def __str__(self):
        return self.nombre_repositorio

class PatentesRepositorios(models.Model):
    repositorio = models.ForeignKey('Repositorios', on_delete=models.CASCADE)
    patente = models.ForeignKey(Patentes, on_delete=models.CASCADE)
    link_patente_repositorio = models.CharField(max_length=100)

    class Meta:
        db_table = 'patentes_repositorios'
    def __str__(self):
        return self.link_patente_repositorio

#Inventores Solicitantes
class InventoresSolicitantes(models.Model):
    nombre_inventor_solicitante = models.CharField(unique=True, max_length=200)

    class Meta:
        db_table = 'inventores_solicitantes'
        verbose_name = "inventor_solicitante"
        verbose_name_plural = "inventores_solicitantes"
        ordering = ['nombre_inventor_solicitante']

    def __str__(self):
        return self.nombre_inventor_solicitante

class PatInvSol(models.Model):
    tipo_pat_inv_sol = models.CharField(max_length=1)
    inventor_solicitante = models.ForeignKey(InventoresSolicitantes, on_delete=models.CASCADE)
    patente = models.ForeignKey('Patentes', on_delete=models.CASCADE)

    class Meta:
        db_table = 'pat_inv_sol'
        verbose_name = "pat_inv_sol"
        ordering = ['tipo_pat_inv_sol']


    def __str__(self):
        return self.tipo_pat_inv_sol

#Categorias	
class CategoriaVt(models.Model):
    nombre_categoria_vt = models.CharField(db_column='nombre_Clasificacion_VT', max_length=45)  # Field name made lowercase.

    class Meta:
        db_table = 'CategoriaVt'
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ['nombre_categoria_vt']

    def __str__(self):
        return self.nombre_categoria_vt


class PatenteCatvt(models.Model):
    patentes_id_patente = models.ForeignKey('Patentes', on_delete=models.CASCADE, db_column='patentes_id_patente')
    categoria_vt_id_categoria_vt = models.ForeignKey(CategoriaVt, on_delete=models.CASCADE, db_column='categoria_vt_id_categoria_vt')  # Field name made lowercase.

    class Meta:
        db_table = 'patente_catVT'

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Título'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
        }
        labels = {
            'title':'', 'description': ''
        }

projects/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from .models import Project
from scraper.models import Ecuacion
from django.db.models import Count
from .forms import ProjectForm
from registration.views import SignUpView
# Create your views here.
class ProjectListView(ListView):
    model = Project

class ProjectDetailView(DetailView):
    model = Project
    
@method_decorator(login_required, name='dispatch')
class ProjectCreate(CreateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('projects:projects')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ProjectCreate, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProjectUpdate(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('projects:update', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name='dispatch')
class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('projects:projects')

projects/templates/projects/project_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar proyecto{% endblock %}
{% block main-content %}
{% include 'projects/includes/projects_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post">{% csrf_token %}
            <p>¿Estás seguro de que quieres borrar <b>"{{ object }}"</b>?</p>
            <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar el proyecto" />
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{project.title}}{% endblock %}
{% block content %}
{% include 'projects/includes/project_menu.html' %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-20 mx-auto">
        
        <div>
          {{project.description|safe}}
          <div style="margin-left:2px;margin-top:4px">
    
            {% for ecu in project.ecuacion_set.all%}
                  
                  <h6><p class="text-muted"><strong>{{ecu.ecuacion}}</strong> ,Patentes:{{ecu.patentes_set.count}}, Fecha:{{ecu.updated}},
                    <a href="{% url 'scraper:ecuacion' ecu.id %}">Ver</a>
                    | <a href="{% url 'scraper:delete' ecu.id %}">Borrar</a>
                  </p></h6>
                  <hr>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear proyecto{% endblock %}
{% block main-content %}
{% include 'projects/includes/projects_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
          <div class="text-center">
            <input type="submit" class="btn btn-primary btn-block" value="Crear proyecto" />
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Proyectos{% endblock %}
{% block main-content %}
{% if not request.user.is_authenticated %}
    <script>window.location.href = 'registration:signup'; </script>
  {% endif %}
{% include 'projects/includes/projects_menu.html' %}
{% if request.user.is_authenticated %}
<main role="main">
  <div class="container mb-4">
    {% for project in project_list|dictsort:"id" reversed %}
      <div class="row mt-3">
        <div class="col-md-9 mx-auto">
          <h2 class="mb-4">{{project.title}}</h2>
          <div>
            <p>{{project.description|striptags|safe|truncatechars:"200"}} ({{project.ecuacion_set.count}} ecuaciones, con {{project.ecuacion_set.patentes_set.count}} patentes)</p>
            <p><a href="{% url 'projects:project' project.id %}">Ver</a>
                | <a href="{% url 'projects:update' project.id %}">Editar</a>
                | <a href="{% url 'projects:delete' project.id %}">Borrar</a>
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% else %}

{% endif%}

{% endblock %}

projects/templates/projects/project_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar Proyecto{% endblock %}
{% block main-content %}
{% include 'projects/includes/projects_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style="color:green;">
              Proyecto editado correctamente. 
              <a href="{% url 'projects:project' project.id project.title|slugify %}">Haz clic aquí para ver el resultado</a>.
            </p>
          {% endif %}
          <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
          <div class="text-center">
            <input type="submit" class="btn btn-primary btn-block" value="Actualizar proyecto" />
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}